# Generated by Django 4.2 on 2023-05-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_totalcartprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startoproduct',
            name='star',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
    ]
